// <auto-generated />
using System;
using HospitalAccessControl.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalAccessControl.Infrastructure.Data.Migrations
{
    [DbContext(typeof(HospitalAccessControlDbContext))]
    partial class HospitalAccessControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HospitalAccessControl.Domain.Entities.AccessLog", b =>
                {
                    b.Property<long>("AccessLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AccessLogId"));

                    b.Property<DateTime>("AccessDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ApplicationName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ClientHost")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DomainLogin")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("bit");

                    b.HasKey("AccessLogId");

                    b.HasIndex("AccessDate")
                        .HasDatabaseName("IX_AccessLog_AccessDate");

                    b.HasIndex("ActionCode")
                        .HasDatabaseName("IX_AccessLog_ActionCode");

                    b.HasIndex("DomainLogin")
                        .HasDatabaseName("IX_AccessLog_DomainLogin");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_AccessLog_PatientId");

                    b.HasIndex("WasSuccessful")
                        .HasDatabaseName("IX_AccessLog_WasSuccessful");

                    b.ToTable("AccessLog", "audit");
                });

            modelBuilder.Entity("HospitalAccessControl.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<int>("ApplicationRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationRoleId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ApplicationRoleId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ApplicationRoles_Code");

                    b.ToTable("ApplicationRoles", "dictionary");
                });

            modelBuilder.Entity("HospitalAccessControl.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("ApplicationUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationUserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DomainLogin")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SamAccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ApplicationUserId");

                    b.HasIndex("DomainLogin")
                        .IsUnique()
                        .HasDatabaseName("UQ_ApplicationUsers_DomainLogin");

                    b.HasIndex("SamAccountName")
                        .IsUnique()
                        .HasDatabaseName("UQ_ApplicationUsers_SamAccountName");

                    b.ToTable("ApplicationUsers", "security");
                });

            modelBuilder.Entity("HospitalAccessControl.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Departments_Code");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Departments_Name");

                    b.ToTable("Departments", "dictionary");
                });

            modelBuilder.Entity("HospitalAccessControl.Domain.Entities.MedicalRecord", b =>
                {
                    b.Property<int>("MedicalRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalRecordId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("RecordTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Treatment")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("MedicalRecordId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_MedicalRecords_CreatedAt");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_MedicalRecords_DepartmentId");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_MedicalRecords_PatientId");

                    b.HasIndex("RecordTypeCode")
                        .HasDatabaseName("IX_MedicalRecords_RecordTypeCode");

                    b.ToTable("MedicalRecords", "medical");
                });

            modelBuilder.Entity("HospitalAccessControl.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GenderCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MedicalNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PatientStatusCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("PatientId");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_Patients_DepartmentId");

                    b.HasIndex("MedicalNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Patients_MedicalNumber");

                    b.HasIndex("PatientStatusCode")
                        .HasDatabaseName("IX_Patients_Status");

                    b.HasIndex("Pesel")
                        .HasDatabaseName("IX_Patients_Pesel");

                    b.HasIndex("LastName", "FirstName")
                        .HasDatabaseName("IX_Patients_LastName_FirstName");

                    b.ToTable("Patients", "medical");
                });

            modelBuilder.Entity("HospitalAccessControl.Domain.Entities.UserDepartmentAccess", b =>
                {
                    b.Property<int>("UserDepartmentAccessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserDepartmentAccessId"));

                    b.Property<int>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("UserDepartmentAccessId");

                    b.HasIndex("ApplicationUserId")
                        .HasDatabaseName("IX_UserDepartmentAccess_ApplicationUserId");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_UserDepartmentAccess_DepartmentId");

                    b.HasIndex("ApplicationUserId", "DepartmentId", "IsActive")
                        .HasDatabaseName("IX_UserDepartmentAccess_User_Department_Active");

                    b.ToTable("UserDepartmentAccess", "security");
                });

            modelBuilder.Entity("HospitalAccessControl.Domain.Entities.UserRoleAssignment", b =>
                {
                    b.Property<int>("UserRoleAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleAssignmentId"));

                    b.Property<int>("ApplicationRoleId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("UserRoleAssignmentId");

                    b.HasIndex("ApplicationRoleId")
                        .HasDatabaseName("IX_UserRoleAssignments_ApplicationRoleId");

                    b.HasIndex("ApplicationUserId")
                        .HasDatabaseName("IX_UserRoleAssignments_ApplicationUserId");

                    b.HasIndex("ApplicationUserId", "ApplicationRoleId", "IsActive")
                        .HasDatabaseName("IX_UserRoleAssignments_User_Role_Active");

                    b.ToTable("UserRoleAssignments", "security");
                });

            modelBuilder.Entity("HospitalAccessControl.Domain.Entities.AccessLog", b =>
                {
                    b.HasOne("HospitalAccessControl.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalAccessControl.Domain.Entities.MedicalRecord", b =>
                {
                    b.HasOne("HospitalAccessControl.Domain.Entities.Department", "Department")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalAccessControl.Domain.Entities.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalAccessControl.Domain.Entities.Patient", b =>
                {
                    b.HasOne("HospitalAccessControl.Domain.Entities.Department", "Department")
                        .WithMany("Patients")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HospitalAccessControl.Domain.Entities.UserDepartmentAccess", b =>
                {
                    b.HasOne("HospitalAccessControl.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("DepartmentAccesses")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalAccessControl.Domain.Entities.Department", "Department")
                        .WithMany("UserDepartmentAccesses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HospitalAccessControl.Domain.Entities.UserRoleAssignment", b =>
                {
                    b.HasOne("HospitalAccessControl.Domain.Entities.ApplicationRole", "ApplicationRole")
                        .WithMany("UserRoleAssignments")
                        .HasForeignKey("ApplicationRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalAccessControl.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationRole");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("HospitalAccessControl.Domain.Entities.ApplicationRole", b =>
                {
                    b.Navigation("UserRoleAssignments");
                });

            modelBuilder.Entity("HospitalAccessControl.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("DepartmentAccesses");

                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("HospitalAccessControl.Domain.Entities.Department", b =>
                {
                    b.Navigation("MedicalRecords");

                    b.Navigation("Patients");

                    b.Navigation("UserDepartmentAccesses");
                });

            modelBuilder.Entity("HospitalAccessControl.Domain.Entities.Patient", b =>
                {
                    b.Navigation("MedicalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
